apiVersion: v2
name: cfgate
description: Gateway API-native Kubernetes operator for Cloudflare Tunnel, DNS, and Access
type: application
version: 1.8.0
appVersion: "0.2.0-alpha.9"
kubeVersion: ">= 1.26.0-0"

keywords:
  - cloudflare
  - tunnel
  - dns
  - access
  - zero-trust
  - gateway-api
  - kubernetes
  - operator

home: https://cfgate.io
icon: https://cfgate.io/icon.png

sources:
  - https://github.com/cfgate/cfgate
  - https://github.com/cfgate/helm-chart

maintainers:
  - name: inherent-design
    url: https://github.com/inherent-design

annotations:
  cfgate.io/operator-image-digest: "sha256:f31bcf0cf413d5b09b6fe1b89caa2d3461e0e8b74e33ae954aa5c15b5ac47d2d"
  artifacthub.io/license: Apache-2.0
  artifacthub.io/category: networking
  artifacthub.io/operator: "true"
  artifacthub.io/operatorCapabilities: Basic Install
  artifacthub.io/prerelease: "true"
  artifacthub.io/images: |
    - name: cfgate
      image: ghcr.io/cfgate/cfgate
