{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "cfgate.fullname" . }}-manager
  labels:
    {{- include "cfgate.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "cfgate.fullname" . }}-manager
subjects:
  - kind: ServiceAccount
    name: {{ include "cfgate.serviceAccountName" . }}
    namespace: {{ include "cfgate.namespace" . }}
{{- end }}
