{{- if .Values.metrics.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cfgate.fullname" . }}-metrics
  namespace: {{ include "cfgate.namespace" . }}
  labels:
    {{- include "cfgate.labels" . | nindent 4 }}
  {{- with .Values.metrics.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: {{ .Values.metrics.service.port }}
      targetPort: metrics
      protocol: TCP
  selector:
    {{- include "cfgate.selectorLabels" . | nindent 4 }}
{{- end }}
