{{- if .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "cfgate.fullname" . }}
  namespace: {{ .Values.metrics.serviceMonitor.namespace | default (include "cfgate.namespace" .) }}
  labels:
    {{- include "cfgate.labels" . | nindent 4 }}
    {{- with .Values.metrics.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  endpoints:
    - port: metrics
      interval: {{ .Values.metrics.serviceMonitor.interval }}
      path: /metrics
  namespaceSelector:
    matchNames:
      - {{ include "cfgate.namespace" . }}
  selector:
    matchLabels:
      {{- include "cfgate.selectorLabels" . | nindent 6 }}
{{- end }}
