// Env is defined in worker-configuration.d.ts (generated by `wrangler types`)

export default {
  async fetch(request: Request, env: Env, ctx: ExecutionContext): Promise<Response> {
    return new Response('Hello World!')
  },
} satisfies ExportedHandler<Env>
