// Env is defined in worker-configuration.d.ts (generated by `wrangler types`)

export default {
  async fetch(_request: Request, _env: Env, _ctx_: ExecutionContext): Promise<Response> {
    return new Response('Hello World!')
  },
} satisfies ExportedHandler<Env>
