apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: echo
  namespace: demo
spec:
  parentRefs:
    - name: cloudflare-tunnel
      namespace: cfgate-system
  hostnames:
    - echo.example.com  # <-- Replace with your subdomain
  rules:
    - backendRefs:
        - name: echo
          port: 80
